# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: documentation

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction -E sphinx
      #----------------------------------------------
      #              link with flake8
      #----------------------------------------------
#      - name: flake8 check syntax or undefined name
#        uses: py-actions/flake8@v2
#        with:
#         ignore: "F401"
#         max-line-length: "100"
#         path: "georges_core"
#         args: "--count --max-line-length=127 --select=E9,F63,F7,F82 --statistics"

#      - name: flake8 check minor things
#        uses: py-actions/flake8@v2
#        with:
#          ignore: "F401"
#          max-line-length: "100"
#          path: "georges_core"
#          args: "--count --exit-zero --count --max-line-length=127 --statistics"

      #----------------------------------------------
      #              Built the doc
      #----------------------------------------------
      - name: Run sphinx
        run: |
          source .venv/bin/activate
          sphinx-build -b html docs build
